### ISSUE TITLE
Fix Regressions in Ganache-Core 2.3.1

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/ganache-core#246]
- [x] Fix Incorrect Transaction Hashes: https://github.com/trufflesuite/ganache-cli/issues/387, https://github.com/trufflesuite/ganache-cli/issues/598, https://github.com/trufflesuite/ganache-cli/issues/403. PR: https://github.com/trufflesuite/ganache-core/pull/243
- [x] Revert State Trie and VM Changes: https://github.com/trufflesuite/ganache-cli/issues/600, https://github.com/trufflesuite/ganache-cli/issues/603, https://github.com/trufflesuite/ganache-core/issues/255 PR: https://github.com/trufflesuite/ganache-core/pull/254
- [x] Fix persisted db issue: https://github.com/trufflesuite/ganache-cli/issues/597
- [x] Ganache-Cli: switch to 100% webpacked lib to ensure the cli is always the same build, also prevents install issues via yarn on windows. https://github.com/trufflesuite/ganache-cli/pull/606 then https://github.com/trufflesuite/ganache-cli/pull/605

**Comment by davidmurdoch** [comment]
Fixed in [v2.3.2 - Bug & Regression Fixes 🐛](https://github.com/trufflesuite/ganache-core/releases/tag/v2.3.2) and [v6.2.4 - Bug & Regression Fixes 🐈](https://github.com/trufflesuite/ganache-cli/releases/tag/v6.2.4)
